title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
plugins:
  - jekyll-default-layout
url: https://clairpred.github.io/

aux_links:
  Template Repository: https://github.com/clairpred/clairpred.github.io
